{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-segregation
  version: {{ version|replace("-", "_") }}

source:
  fn: segregation_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/segregation_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/segregation/segregation_{{ version }}.tar.gz
  sha256: 47e425115caa5f7d2e64ce20bc34955e815198d4dca58ebdc345b04dff78c6ae

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-data.table
  run:
    - r-base
    - r-data.table

test:
  commands:
    - $R -e "library('segregation')"           # [not win]
    - "\"%R%\" -e \"library('segregation')\""  # [win]

about:
  home: http://github.com/elbersb/segregation
  license: MIT
  license_file: LICENSE
  summary: Computes entropy-based segregation indices, as developed by Theil (1971) <isbn:978-0471858454>, with a focus on  the Mutual Information Index (M) and Theil's Information Index (H).  The M, further described by Mora and Ruiz-Castillo (2011) <doi:10.1111/j.1467-9531.2011.01237.x> and Frankel and Volij (2011) <doi:10.1016/j.jet.2010.10.008>,  is
    a measure of segregation that is highly decomposable. The package provides tools to decompose the index by units and groups (local segregation),  and by within and between terms. Includes standard error estimation by bootstrapping.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo
