{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-segregation
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/segregation_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/segregation/segregation_{{ version }}.tar.gz
  sha256: 551cc749c1e7ced87cb0418dace12fc480f9dea26e05ab2f7d89a2a236a64dd0

build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-rcppprogress
    - r-checkmate
    - r-data.table
  run:
    - r-base
    - r-rcpp
    - r-rcppprogress
    - r-checkmate
    - r-data.table

test:
  commands:
    - $R -e "library('segregation')"           # [not win]
    - "\"%R%\" -e \"library('segregation')\""  # [win]

about:
  home: https://elbersb.github.io/segregation/
  dev_url: https://github.com/elbersb/segregation/
  license: MIT
  summary: Computes entropy-based segregation indices, as developed by Theil (1971) <isbn:978-0471858454>, with a focus on  the Mutual Information Index (M) and Theil's Information Index (H).  The M, further described by Mora and Ruiz-Castillo (2011) <doi:10.1111/j.1467-9531.2011.01237.x> and Frankel and Volij (2011) <doi:10.1016/j.jet.2010.10.008>,  is
    a measure of segregation that is highly decomposable. The package provides tools to decompose the index by units and groups (local segregation),  and by within and between terms. Includes standard error estimation by bootstrapping.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo
