appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: U590V9RXmj49g+KEjQUwGrlcwefyjcdMafCcFfGjVSHsTqgxUcgDVOuVERIZTnHhG2wtpOlxlmSKGpEVIyX9c4HbvrzzRFNU7vaCdC+jLBRJzntHtoQ6XdwF/KpoYpIp8M6qDM5xrwggqtbr+jTEfOPMKywvqmaC2niOikhgq8rAJmfmvfuE9dm2EeiBhh3XUQ+Z1Z+gEQgHH25KhO6OPoUDeEH6mX304HmD3bWeDp/lXMt1TyiL5v3fZrSS5LTodgjcZnbbxFmQGUZBksQag8Ib1AA6ohRgTkTvjhAQClCMli36HbBrbneAB1Ndy/tZAiWMGbfDeDf9YbnWfOb3Ra7ORsXNUzRLuLBOivpHzqD5ubufMheJk49y08vu+2HpAE1XcfacQaZ9IXTr/+fD6KrXMEqF6q8TzaSOuu58XGvtnEIzMbmxw7fiRFYz2MeN9YqupDXlgyClFB9BUges7OE/UWk3tsd/vKsIyV1/12EZCjaB4wK/i6cHH4EB8/0fdwRJW+6gj31z0CvpMM9rrsjNroMgnvYEwlA92UMUAQp73RDeX38LBFZFpHse/lmYGX0+6tz336/1I/m0iLe2H6ifTLRVB6tCr075dhyqVOneKJNr8VRM+8NTEf7BMazhj0W7nQjqy6XqVmwecYjBNDSHexTgdADlaFUm2KQx6jU=
